### ISSUE TITLE
User-Change Password

### ISSUE THREAD

**Issue by karansahh** [chapairoshan/VROOM#41]
Req#Id: U9
Title: Investigation of Password Change Functionality Issue (Req#Id: U9)

Description:
The current issue, as outlined in Req#Id: U9, pertains to the inability of users to change their passwords as expected. This GitHub issue is opened to initiate a detailed investigation into the root cause(s) of this functionality breakdown and to propose appropriate remedial actions.

Problem Statement:
Users are encountering difficulties when attempting to change their passwords. This issue disrupts the intended user experience and requires immediate attention to ensure seamless functionality.

Steps to Reproduce:
Navigate to the "Change Password" section in the user account settings.
Enter current password, new password, and confirmation.
Attempt to save changes.
Observe any error messages or unexpected behavior.

**Comment by chapairoshan** [comment]
Hi @karansahh There was no work done on the forgot password function at the time of testing hence it didn't work properly. but now that the project is done and complete can you please pull the latest changes from the main branch and test once more and try to reproduce this issue and it still is there please reopen this issue. Thank you.
